#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop hippocampus-daemon.service || true
    systemctl stop hippocampus-summarize.timer || true
    systemctl disable hippocampus-daemon.service || true
    systemctl disable hippocampus-summarize.timer || true
    systemctl daemon-reload || true
fi
